local o = vim.opt

o.guifont = 'JetBrainsMono Nerd Font:h12'
o.diffopt = vim.o.diffopt .. ',algorithm:patience'
o.updatetime = 700
o.timeoutlen = 500
o.clipboard = 'unnamed'
o.completeopt = 'menuone,noinsert,noselect'
o.termguicolors = true
o.wildoptions = 'pum'
o.pumblend = 17
o.hidden = true
o.splitright = true
o.splitbelow = true
o.scrolloff = 10
o.mouse = 'n'
o.ignorecase = true
o.smartcase = true
o.smarttab = true
o.hlsearch = false
o.guicursor = ''
o.signcolumn = 'yes:2'
o.number = true
o.relativenumber = true
o.cursorline = true
o.breakindent = false
o.linebreak = false
o.wrap = false
o.swapfile = false
o.undofile = true
o.tabstop = 4
o.shiftwidth = 4
o.softtabstop = 4
o.expandtab = true
o.smartindent = true
o.formatoptions = string.gsub(vim.bo.formatoptions, "[co]", "")

vim.g.loaded_netrwPlugin = 1
vim.g.completion_confirm_key = ""
